package javen.example.com.smartnews.main.fragment.home.bean.top_news;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import javen.example.com.smartnews.main.fragment.home.bean.top_news.NewsBean;

import javen.example.com.smartnews.main.fragment.home.bean.top_news.NewsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsBeanDaoConfig;

    private final NewsBeanDao newsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsBeanDaoConfig = daoConfigMap.get(NewsBeanDao.class).clone();
        newsBeanDaoConfig.initIdentityScope(type);

        newsBeanDao = new NewsBeanDao(newsBeanDaoConfig, this);

        registerDao(NewsBean.class, newsBeanDao);
    }
    
    public void clear() {
        newsBeanDaoConfig.clearIdentityScope();
    }

    public NewsBeanDao getNewsBeanDao() {
        return newsBeanDao;
    }

}
