package javen.example.com.smartnews.main.fragment.home.bean.top_news;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import javen.example.com.smartnews.main.fragment.home.bean.top_news.TopNewsBean;

import javen.example.com.smartnews.main.fragment.home.bean.top_news.TopNewsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topNewsBeanDaoConfig;

    private final TopNewsBeanDao topNewsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topNewsBeanDaoConfig = daoConfigMap.get(TopNewsBeanDao.class).clone();
        topNewsBeanDaoConfig.initIdentityScope(type);

        topNewsBeanDao = new TopNewsBeanDao(topNewsBeanDaoConfig, this);

        registerDao(TopNewsBean.class, topNewsBeanDao);
    }
    
    public void clear() {
        topNewsBeanDaoConfig.clearIdentityScope();
    }

    public TopNewsBeanDao getTopNewsBeanDao() {
        return topNewsBeanDao;
    }

}
