package javen.example.com.smartnews.db.news_channel;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import javen.example.com.smartnews.db.news_channel.NewsChannelBean;
import javen.example.com.smartnews.main.fragment.home.bean.top_news.NewsBean;

import javen.example.com.smartnews.db.news_channel.NewsChannelBeanDao;
import javen.example.com.smartnews.main.fragment.home.bean.top_news.NewsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelBeanDaoConfig;
    private final DaoConfig newsBeanDaoConfig;

    private final NewsChannelBeanDao newsChannelBeanDao;
    private final NewsBeanDao newsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelBeanDaoConfig = daoConfigMap.get(NewsChannelBeanDao.class).clone();
        newsChannelBeanDaoConfig.initIdentityScope(type);

        newsBeanDaoConfig = daoConfigMap.get(NewsBeanDao.class).clone();
        newsBeanDaoConfig.initIdentityScope(type);

        newsChannelBeanDao = new NewsChannelBeanDao(newsChannelBeanDaoConfig, this);
        newsBeanDao = new NewsBeanDao(newsBeanDaoConfig, this);

        registerDao(NewsChannelBean.class, newsChannelBeanDao);
        registerDao(NewsBean.class, newsBeanDao);
    }
    
    public void clear() {
        newsChannelBeanDaoConfig.clearIdentityScope();
        newsBeanDaoConfig.clearIdentityScope();
    }

    public NewsChannelBeanDao getNewsChannelBeanDao() {
        return newsChannelBeanDao;
    }

    public NewsBeanDao getNewsBeanDao() {
        return newsBeanDao;
    }

}
