package javen.example.com.commonlibrary.bean.news;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import javen.example.com.commonlibrary.bean.news.NewsSearchHistoryBean;
import javen.example.com.commonlibrary.bean.news.NewsChannelBean;
import javen.example.com.commonlibrary.bean.news.NewsBean;

import javen.example.com.commonlibrary.bean.news.NewsSearchHistoryBeanDao;
import javen.example.com.commonlibrary.bean.news.NewsChannelBeanDao;
import javen.example.com.commonlibrary.bean.news.NewsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsSearchHistoryBeanDaoConfig;
    private final DaoConfig newsChannelBeanDaoConfig;
    private final DaoConfig newsBeanDaoConfig;

    private final NewsSearchHistoryBeanDao newsSearchHistoryBeanDao;
    private final NewsChannelBeanDao newsChannelBeanDao;
    private final NewsBeanDao newsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsSearchHistoryBeanDaoConfig = daoConfigMap.get(NewsSearchHistoryBeanDao.class).clone();
        newsSearchHistoryBeanDaoConfig.initIdentityScope(type);

        newsChannelBeanDaoConfig = daoConfigMap.get(NewsChannelBeanDao.class).clone();
        newsChannelBeanDaoConfig.initIdentityScope(type);

        newsBeanDaoConfig = daoConfigMap.get(NewsBeanDao.class).clone();
        newsBeanDaoConfig.initIdentityScope(type);

        newsSearchHistoryBeanDao = new NewsSearchHistoryBeanDao(newsSearchHistoryBeanDaoConfig, this);
        newsChannelBeanDao = new NewsChannelBeanDao(newsChannelBeanDaoConfig, this);
        newsBeanDao = new NewsBeanDao(newsBeanDaoConfig, this);

        registerDao(NewsSearchHistoryBean.class, newsSearchHistoryBeanDao);
        registerDao(NewsChannelBean.class, newsChannelBeanDao);
        registerDao(NewsBean.class, newsBeanDao);
    }
    
    public void clear() {
        newsSearchHistoryBeanDaoConfig.clearIdentityScope();
        newsChannelBeanDaoConfig.clearIdentityScope();
        newsBeanDaoConfig.clearIdentityScope();
    }

    public NewsSearchHistoryBeanDao getNewsSearchHistoryBeanDao() {
        return newsSearchHistoryBeanDao;
    }

    public NewsChannelBeanDao getNewsChannelBeanDao() {
        return newsChannelBeanDao;
    }

    public NewsBeanDao getNewsBeanDao() {
        return newsBeanDao;
    }

}
